runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

# This is apparently not needed in the flexible environment.
# handlers:
# - url: .*
# script: app.app

runtime_config:
  python_version: 2

# To get the connection name run the following:
#   gcloud sql instances describe team1-lastride
# where `team1-lastride` is the name of the database on Google Cloud Platform.
# Look for a line which starts with `connectionName:`
# alternatively, you could do:
#   gcloud sql instances describe team1-lastride | grep connectionName
env_variables:
    # It seems that this is the name of the socket to connect to. The
    # cloud-proxy-will set up a socket on your computer that matches this, and
    # the deployed version will also connect to such a proxy.
    CLOUDSQL_CONNECTION_NAME: "global-env-166817:us-east1:team1-lastride"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "lastridebestride"

beta_settings:
  cloud_sql_instances: "global-env-166817:us-east1:team1-lastride"
